[package]
name = "musql"
version = "0.5.0"
authors = ["F. Rilling <contact@rilling.dev>"]
license = "GPL-3"
readme = "README.md"
repository = "https://github.com/RillingDev/musql"
description = """
Music tags to SQL conversion.
"""
edition = "2024"

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "3.0.2"
anyhow = "1.0.92"
walkdir = "2.5.0"
serde_json = "1.0.133"
symphonia = { version = "0.6.0", features = ["all"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
